platform :ios, '14.0'

target 'Example - Pod' do
  # The 'use_frameworks!' option builds the pods as dynamic frameworks instead of static libs.
  use_frameworks!

  # Pods for Example
  pod 'ATTNSDKFramework', :path => '../'

end
