platform :ios, '10.0'

target 'ExampleSwift - Pod' do
  # The 'use_frameworks!' option builds the pods as dynamic frameworks instead of static libs.
  use_frameworks!

  # Pods for Example
  pod 'attentive-ios-sdk', '0.4.3-beta.1'

end
